language: c
before_install: wget --no-check-certificate https://dl.bintray.com/mitchellh/packer/0.6.0_linux_amd64.zip && unzip -d packer 0.6.0_linux_amd64.zip
before_script: export PATH=$PATH:$PWD/packer
script: packer validate ubuntu1404-minimal-amd64.json
